version: '3.8'

services: 
  # docker compose up zkp-server
  zkp-server:
    image: zkp-server:latest
    container_name: zkp-server
    build:
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    init: true
    restart: always
  
  # docker compose run --rm zkp-client register
  # docker compose run --rm zkp-client login
  zkp-client:
    image: zkp-client:latest
    build:
      dockerfile: Dockerfile.client
    network_mode: host
    init: true
    depends_on:
      - zkp-server
