version: '3.8'

services:
  # docker compose up zkp-server
  zkp-server:
    image: zkp-server:latest
    container_name: zkp-server
    build:
      dockerfile: Dockerfile.server
    command: -l 0.0.0.0
    environment:
      - RUST_LOG_STYLE=always
    ports:
      - "3000:3000"
    init: true
    restart: always

  # docker compose run zkp-client register
  # docker compose run zkp-client login
  zkp-client:
    image: zkp-client:latest
    build:
      dockerfile: Dockerfile.client
    network_mode: host
    init: true
    depends_on:
      - zkp-server
